MyRecipeBuddy/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

from postDetail import views as postDetail_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls')),
    path('postDetail/', include('postDetail.urls')),
    path('login/', include('login.urls')),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('comment/create/<int:content_id>/', postDetail_views.comment_create, name='comment_create'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

login/urls.py
from django.urls import path 
from django.contrib.auth import views as auth_views 
from . import views

urlpatterns = [ 
    path('', views.loginPage, name='loginPage'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'), 
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
 path('', views.mainpage, name='mainpage'),
]

postDetail/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.postDetailPage, name='postDetailPage'),
    path('comment/update/<int:comment_id>/', views.comment_update, name='comment_update'), 
    path('comment/delete/<int:comment_id>/', views.comment_delete, name='comment_delete'), 
]

login/models.py
from django.db import models
from django.utils import timezone

# 장고는 SQL 작성없이 데이터 처리 가능
# python manage.py makemigrations
# 실제 데이터베이스 모델에 적용하기 위한 python manage.py migrate

class LoginContent(models.Model):
 email = models.EmailField(max_length=60, unique=True)
 password = models.CharField(max_length=60)
 pub_date = models.DateTimeField(default=timezone.now) # pub_date 필드에 default 값을 추가

main/models.py
from django.db import models

# 장고는 SQL 작성없이 데이터 처리 가능
class MainContent(models.Model):
 title = models.CharField(max_length=200)
 content = models.TextField()
 pub_date = models.DateField('date published')

postDetail/models.py
from django.db import models
from django.contrib.auth.models import User 

class PostContent(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    pub_date = models.DateField('date published')
    image = models.ImageField(upload_to='post_images/', blank=True, null=True)

    def __str__(self):
        return self.title
   


# 댓글 기능 추가
class Comment(models.Model): 
    author = models.ForeignKey(User, on_delete=models.CASCADE) 
    content_list = models.ForeignKey(PostContent, on_delete=models.CASCADE) 
    content = models.TextField() 
    create_date = models.DateTimeField(auto_now_add=True) 
    modify_date = models.DateTimeField(auto_now=True)

login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm 
from django.contrib.auth.models import User

# 사용자로부터 이메일과 비밀번호를 입력받음

class LoginForm(forms.Form):
    email = forms.EmailField(label='Email', max_length=60)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

class SignupForm(UserCreationForm): 
    email = forms.EmailField() 
    class Meta: 
        model = User 
        fields = ("username", "password1", "password2", "email") 

postDetail/forms.py
from .models import Comment 
from django import forms 
 
class CommentForm(forms.ModelForm): 
    class Meta: 
        model = Comment 
        fields = ('content',)

login/views.py
# views.py 파일 (login 앱)
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib import messages
from .forms import LoginForm
from .forms import SignupForm 

def loginPage(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(request, username=email, password=password)
            if user is not None:
                login(request, user)
                return redirect('mainpage')  # 로그인 성공 후 리디렉션할 URL 이름 사용
            else:
                messages.error(request, '이메일 또는 비밀번호가 틀립니다. 다시 시도해주세요.')
    else:
        form = LoginForm()

    return render(request, 'pages/loginPage.html', {'form': form})

def signup(request): 
    if request.method == "POST": 
        form = SignupForm(request.POST) 
        if form.is_valid(): 
            user = form.save() 
            login(request, user) 
            return redirect('/')  # 리디렉션을 들여쓰기를 맞춰서 if 블록 안으로 이동
    else: 
        form = SignupForm() 

    return render(request, 'pages/signup.html', {'form': form})

main/views.py
from django.shortcuts import render
# from .models import MainContent

# 페이지 제작 명령어 -> python manage.py startapp 페이지명
# django 실행 python manage.py runserver

# Create your views here.
def mainpage(request) :

  # 해당 content_list의 데이터를 다른 html파일에 적용 후 html을 리턴 가능(render함수)
  # mainpage_list = MainContent.objects.order_by('-pub_date')
  # content = {'mainpage_list': mainpage_list}

  return render(request, 'pages/mainpage.html')

postDetail/views.py
from django.core.exceptions import PermissionDenied 
from django.shortcuts import render, redirect
from .models import PostContent, Comment
from .forms import CommentForm 
from django.contrib.auth.decorators import login_required 

def postDetailPage(request):
    post_list = PostContent.objects.order_by('-pub_date')
    post_content = {'post_list': post_list}

    return render(request, 'pages/postDetailPage.html', post_content)


@login_required(login_url='postDetail:login') #비로그인 상태에서 댓글 작성 시 로그인 화면으로 이동
def comment_create(request, content_id): #댓글 기능
    content_list = get_object_or_404(PostContent, pk=content_id) 
 
    if request.method == 'POST': 
        form = CommentForm(request.POST) 
        if form.is_valid(): 
            comment = form.save(commit=False) 
            comment.content_list = content_list 
            comment.author = request.user 
            comment.save() 
            return redirect('detail', content_id=content_list.id) 
    else: 
        form = CommentForm() 
        context = {'content_list': content_list, 'form': form} 
    return render(request, 'pages/postDetailPage.html', {'post_content': post_content})


#댓글 수정, 삭제 기능 (로그인한 계정만 해당 기능 사용 가능)
@login_required(login_url='postDetail:login') 
def comment_update(request, comment_id): 
    comment = get_object_or_404(Comment, pk=comment_id) 
 
    if request.user != comment.author: 
        raise PermissionDenied 
 
    if request.method == 'POST': 
        form = CommentForm(request.POST, instance=comment) 
        if form.is_valid(): 
            comment = form.save(commit=False) 
            comment.save() 
            return redirect('detail', content_id=comment.content_list.id) 
    else: 
        form = CommentForm(instance=comment) 
 
    context = {'comment': comment, 'form': form} 
    return render(request, 'pages/comment_form.html', context) 

@login_required(login_url='postDetail:login') 
def comment_delete(request, comment_id): 
    comment = get_object_or_404(Comment, pk=comment_id) 
 
    if request.user != comment.author: 
        raise PermissionDenied 
    else: 
        comment.delete() 
    return redirect('detail', content_id=comment.content_list.id)

templates/pages/comment_form.html
<!--로그인 했을 경우에만 댓글 수정, 삭제 기능을 사용할 수 있다-->

{% extends 'postDetailPage.html' %} {% block content %}
<h2>update comment</h2>
<section class="mb-5">
  <div class="card bg-light">
    <div class="card-body">
      <form
        method="post"
        class="mb-4"
        action="{% url 'comment_update' comment.id %}"
      >
        {% csrf_token %}
        <textarea id="content" name="content" class="form-control" rows="3">
         {{ form.content.value }}
        </textarea>
        <button type="submit" class="btn btn-primary">submit</button>
      </form>
    </div>
  </div>
</section>
{% endblock %}

templates/pages/footer.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>New Age - Start Bootstrap Theme</title>
    <!-- <link rel="icon" type="image/x-icon" href="assets/favicon.ico" /> -->
    <!-- Bootstrap icons-->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
      rel="stylesheet"
    />
    <!-- Google fonts-->
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Newsreader:ital,wght@0,600;1,600&amp;display=swap"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,300;0,500;0,600;0,700;1,300;1,500;1,600;1,700&amp;display=swap"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,400;1,400&amp;display=swap"
      rel="stylesheet"
    />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="static/styles.css" rel="stylesheet" />
  </head>
  <body id="page-top">
    <!-- Footer-->
    <footer class="bg-black text-center py-5">
      <div class="container px-5">
        <div class="text-white-50 small">
          <div class="mb-2">&copy; Your Website 2024. All Rights Reserved.</div>
          <a href="#!">Privacy</a>
          <span class="mx-1">&middot;</span>
          <a href="#!">Terms</a>
          <span class="mx-1">&middot;</span>
          <a href="#!">FAQ</a>
        </div>
      </div>
    </footer>
    <!-- Feedback Modal-->
    <div
      class="modal fade"
      id="feedbackModal"
      tabindex="-1"
      aria-labelledby="feedbackModalLabel"
      aria-hidden="true"
    >
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header bg-gradient-primary-to-secondary p-4">
            <h5 class="modal-title font-alt text-white" id="feedbackModalLabel">
              Send feedback
            </h5>
            <button
              class="btn-close btn-close-white"
              type="button"
              data-bs-dismiss="modal"
              aria-label="Close"
            ></button>
          </div>
          <div class="modal-body border-0 p-4">
            <!-- * * * * * * * * * * * * * * *-->
            <!-- * * SB Forms Contact Form * *-->
            <!-- * * * * * * * * * * * * * * *-->
            <!-- This form is pre-integrated with SB Forms.-->
            <!-- To make this form functional, sign up at-->
            <!-- https://startbootstrap.com/solution/contact-forms-->
            <!-- to get an API token!-->
            <form id="contactForm" data-sb-form-api-token="API_TOKEN">
              <!-- Name input-->
              <div class="form-floating mb-3">
                <input
                  class="form-control"
                  id="name"
                  type="text"
                  placeholder="Enter your name..."
                  data-sb-validations="required"
                />
                <label for="name">Full name</label>
                <div class="invalid-feedback" data-sb-feedback="name:required">
                  A name is required.
                </div>
              </div>
              <!-- Email address input-->
              <div class="form-floating mb-3">
                <input
                  class="form-control"
                  id="email"
                  type="email"
                  placeholder="name@example.com"
                  data-sb-validations="required,email"
                />
                <label for="email">Email address</label>
                <div class="invalid-feedback" data-sb-feedback="email:required">
                  An email is required.
                </div>
                <div class="invalid-feedback" data-sb-feedback="email:email">
                  Email is not valid.
                </div>
              </div>
              <!-- Phone number input-->
              <div class="form-floating mb-3">
                <input
                  class="form-control"
                  id="phone"
                  type="tel"
                  placeholder="(123) 456-7890"
                  data-sb-validations="required"
                />
                <label for="phone">Phone number</label>
                <div class="invalid-feedback" data-sb-feedback="phone:required">
                  A phone number is required.
                </div>
              </div>
              <!-- Message input-->
              <div class="form-floating mb-3">
                <textarea
                  class="form-control"
                  id="message"
                  type="text"
                  placeholder="Enter your message here..."
                  style="height: 10rem"
                  data-sb-validations="required"
                ></textarea>
                <label for="message">Message</label>
                <div
                  class="invalid-feedback"
                  data-sb-feedback="message:required"
                >
                  A message is required.
                </div>
              </div>
              <!-- Submit success message-->
              <!---->
              <!-- This is what your users will see when the form-->
              <!-- has successfully submitted-->
              <div class="d-none" id="submitSuccessMessage">
                <div class="text-center mb-3">
                  <div class="fw-bolder">Form submission successful!</div>
                  To activate this form, sign up at
                  <br />
                  <a href="https://startbootstrap.com/solution/contact-forms"
                    >https://startbootstrap.com/solution/contact-forms</a
                  >
                </div>
              </div>
              <!-- Submit error message-->
              <!---->
              <!-- This is what your users will see when there is-->
              <!-- an error submitting the form-->
              <div class="d-none" id="submitErrorMessage">
                <div class="text-center text-danger mb-3">
                  Error sending message!
                </div>
              </div>
              <!-- Submit Button-->
              <div class="d-grid">
                <button
                  class="btn btn-primary rounded-pill btn-lg disabled"
                  id="submitButton"
                  type="submit"
                >
                  Submit
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

templates/pages/header.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>New Age - Start Bootstrap Theme</title>
    <!-- <link rel="icon" type="image/x-icon" href="assets/favicon.ico" /> -->
    <!-- Bootstrap icons-->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
      rel="stylesheet"
    />
    <!-- Google fonts-->
    <link rel="preconnect" href="https://fonts.gstatic.com" />
    <link
      href="https://fonts.googleapis.com/css2?family=Newsreader:ital,wght@0,600;1,600&amp;display=swap"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Mulish:ital,wght@0,300;0,500;0,600;0,700;1,300;1,500;1,600;1,700&amp;display=swap"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,400;1,400&amp;display=swap"
      rel="stylesheet"
    />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="static/styles.css" rel="stylesheet" />
  </head>
  <body id="page-top">
    <!-- templates/pages/header.html -->
    <nav
      class="navbar navbar-expand-lg navbar-light fixed-top shadow-sm"
      id="mainNav"
    >
      <div class="container px-5">
        <a class="navbar-brand fw-bold" href="{% url 'mainpage' %}"
          >MyRecipeBuddy</a
        >
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarResponsive"
          aria-controls="navbarResponsive"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          Menu
          <i class="bi-list"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ms-auto me-4 my-3 my-lg-0">
            <li class="nav-item">
              <a class="nav-link me-lg-3" href="#about">회사 소개</a>
            </li>
            <li class="nav-item">
              <a class="nav-link me-lg-3" href="{% url 'postDetailPage' %}"
                >레시피 게시판</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link me-lg-3" href="#contact">문의하기</a>
            </li>
            <!-- 로그인 -->
            <!-- 로그인 시 login이라는 표시와 함께 이메일 표시 / 로그아웃 시 logout 표시-->
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link me-lg-3" href="{% url 'loginPage' %}"
                >{{ user.username }} (logout)</a
              >
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link me-lg-3" href="{% url 'loginPage' %}">login</a>
            </li>
            {% endif %}
            <!-- 로그인-->
          </ul>
          <button
            class="btn btn-primary rounded-pill px-3 mb-2 mb-lg-0"
            data-bs-toggle="modal"
            data-bs-target="#feedbackModal"
          >
            <span class="d-flex align-items-center">
              <i class="bi-chat-text-fill me-2"></i>
              <span class="small">Send Feedback</span>
            </span>
          </button>
        </div>
      </div>
    </nav>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="/static/scripts.js"></script>
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <!-- * *                               SB Forms JS                               * *-->
    <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
  </body>
</html>

templates/pages/loginPage.html
<!-- loginPage.html -->
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login</title>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="/static/styles.css" rel="stylesheet" />
    <style>
      #loginpage {
        padding-top: 56px;
      }

      #main-content {
        margin-top: 80px;
      }
    </style>
    <script>
      function logLoginAttempt() {
        console.log("사용자가 로그인을 시도하였습니다.");
      }
    </script>
  </head>
  <body id="page-top loginpage">
    {% include "pages/header.html" %}
    <div id="main-content">
      {% block content %}
      <h2>Login</h2>
      {% if messages %} {% for message in messages %}
      <p>{{ message }}</p>
      {% endfor %} {% endif %}
      <form
        method="post"
        action="{% url 'loginPage' %}"
        onsubmit="logLoginAttempt()"
      >
        {% csrf_token %}
        <table>
          <tr>
            <td>{{ form.email.label_tag }}</td>
            <td>{{ form.email }}</td>
          </tr>
          <tr>
            <td>{{ form.password.label_tag }}</td>
            <td>{{ form.password }}</td>
          </tr>
        </table>
        <input type="submit" value="Login" />
      </form>
      <a href="{% url 'signup' %}">회원가입</a>
      {% endblock %}
    </div>
    {% include "pages/footer.html" %}
  </body>
</html>

templates/pages/postDetailPage.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>게시판 상세 페이지</title>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="/static/styles.css" rel="stylesheet" />
    <style>
      #postDetailPage {
        padding-top: 56px;
      }

      #main-content {
        margin-top: 80px;
      }
    </style>
  </head>
  <body id="page-top postDetailPage">
    {% include "pages/header.html" %}
    <div id="main-content">
      <!--게시판 상세-->
      <div>
        <h1>게시판 상세 페이지</h1>
        {% if post_list %}
          {% for post_content in post_list %}
            <hr />
            <h3>{{ post_content.title }}</h3>
            {% if post_content.image %}
              <img
                src="{{ post_content.image.url }}"
                alt="Post Image"
                style="width: 200px; height: 200px"
              />
            {% endif %}
            <h5>{{ post_content.content }}</h5>
            <p>Published on: {{ post_content.pub_date }}</p>
            <!--댓글 기능-->
            <section class="mb-5">
              <div class="card bg-light">
                <div class="card-body">
                  <form
                    method="post"
                    class="mb-4"
                    action="{% url 'postDetailPage' %}"
                  >
                    {% csrf_token %}
                    <textarea
                      id="content"
                      name="content"
                      class="form-control"
                      rows="3"
                      placeholder="내용을 입력해주세요."
                    ></textarea>
                    <button type="submit" class="btn btn-primary">submit</button>
                  </form>
                  {% for comment in post_content.comment_set.all %}
                    <div class="d-flex">
                      <div class="ms-3">
                        <div class="fw-bold">
                          {{ comment.author.username }} &nbsp;&nbsp; {{ comment.create_date }}
                          <!--댓글 수정, 삭제 기능 추가-->
                          {% if comment.create_date != comment.modify_date %}
                            / 수정일자: {{ comment.modify_date }}
                          {% endif %}
                          {% if request.user == comment.author %}
                            
                              href="{% url 'comment_update' comment.id  %}"
                              class="btn btn-sm btn-outline secondary"
                            >수정</a>
                            
                              href="{% url 'comment_delete' comment.id  %}"
                              class="btn btn-sm btn-outline secondary"
                            >삭제</a>
                          {% endif %}
                        </div>
                        {{ comment.content }}
                      </div>
                    </div>
                    <br />
                  {% endfor %}
                </div>
              </div>
            </section>
            <!--댓글 기능-->
          {% endfor %}
        {% else %}
          <p>content가 없습니다.</p>
        {% endif %}
      </div>
    </div>
    {% include "pages/footer.html" %}
  </body>
</html>

templates/pages/signup.html
<!DOCTYPE html>
<html lang="ko">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="/static/styles.css" rel="stylesheet" />
    <style>
      #signup {
        padding-top: 56px;
      }

      #main-content {
        margin-top: 80px;
      }
    </style>
  </head>
  <body id="page-top signup">
    {% include "pages/header.html" %}
    <div id="main-content">
      {% block content %}
      <h2>signup</h2>
      <form
        method="post"
        action="{% url 'signup' %}"
        onsubmit="logSignupAttempt()"
      >
        {% csrf_token %} {{form.as_p}}
        <input type="submit" value="Signup" />
      </form>
      {% endblock %}
    </div>
    {% include "pages/footer.html" %}
  </body>
</html>